# Generated by Django 4.1.5 on 2023-01-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='user_id',
            new_name='user',
        ),
    ]
