# Generated by Django 4.1.5 on 2023-01-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_rename_product_id_recommendation_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='product',
            new_name='product_ID',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='user',
            new_name='user_ID',
        ),
    ]
