# Generated by Django 4.1.5 on 2023-01-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_rename_product_recommendation_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
