# Generated by Django 4.1.5 on 2023-01-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_product_image_product_pname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
