# Generated by Django 4.1.5 on 2023-01-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0009_user_email_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
